--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-11-04 13:41:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 219 (class 1255 OID 40980)
-- Name: update_stock_after_insert(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_stock_after_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
BEGIN
	UPDATE produk
	SET stok = stok - NEW.jumlah
	WHERE no = NEW.no_produk;

	RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_stock_after_insert() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 32777)
-- Name: produk; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produk (
    no integer NOT NULL,
    nama_produk character varying(50),
    berat character varying(10),
    harga_beli integer,
    harga_jual integer,
    stok integer
);


ALTER TABLE public.produk OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 40968)
-- Name: produk_no_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produk ALTER COLUMN no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produk_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 40970)
-- Name: transaksi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaksi (
    id integer NOT NULL,
    nama_pelanggan character varying(255) NOT NULL,
    no_produk integer NOT NULL,
    tanggal date NOT NULL,
    jumlah integer NOT NULL
);


ALTER TABLE public.transaksi OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 40969)
-- Name: transaksi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaksi ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.transaksi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4843 (class 0 OID 32777)
-- Dependencies: 215
-- Data for Name: produk; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.produk (no, nama_produk, berat, harga_beli, harga_jual, stok) FROM stdin;
\.


--
-- TOC entry 4846 (class 0 OID 40970)
-- Dependencies: 218
-- Data for Name: transaksi; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaksi (id, nama_pelanggan, no_produk, tanggal, jumlah) FROM stdin;
\.


--
-- TOC entry 4852 (class 0 OID 0)
-- Dependencies: 216
-- Name: produk_no_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produk_no_seq', 7, true);


--
-- TOC entry 4853 (class 0 OID 0)
-- Dependencies: 217
-- Name: transaksi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaksi_id_seq', 15, true);


--
-- TOC entry 4695 (class 2606 OID 32781)
-- Name: produk produk_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produk
    ADD CONSTRAINT produk_pkey PRIMARY KEY (no);


--
-- TOC entry 4697 (class 2606 OID 40974)
-- Name: transaksi transaksi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaksi
    ADD CONSTRAINT transaksi_pkey PRIMARY KEY (id);


--
-- TOC entry 4699 (class 2620 OID 40981)
-- Name: transaksi update_stock; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_stock AFTER INSERT ON public.transaksi FOR EACH ROW EXECUTE FUNCTION public.update_stock_after_insert();


--
-- TOC entry 4698 (class 2606 OID 40975)
-- Name: transaksi no_produk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaksi
    ADD CONSTRAINT no_produk FOREIGN KEY (no_produk) REFERENCES public.produk(no) NOT VALID;


-- Completed on 2024-11-04 13:41:34

--
-- PostgreSQL database dump complete
--

