--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-11-04 13:38:07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4850 (class 1262 OID 32776)
-- Name: sembako_sejahtera; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE sembako_sejahtera WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_Indonesia.1252';


ALTER DATABASE sembako_sejahtera OWNER TO postgres;

\connect sembako_sejahtera

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 32777)
-- Name: produk; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produk (
    no integer NOT NULL,
    nama_produk character varying(50),
    berat character varying(10),
    harga_beli integer,
    harga_jual integer,
    stok integer
);


ALTER TABLE public.produk OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 40968)
-- Name: produk_no_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produk ALTER COLUMN no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produk_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 40970)
-- Name: transaksi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaksi (
    id integer NOT NULL,
    nama_pelanggan character varying(255) NOT NULL,
    no_produk integer NOT NULL,
    tanggal date NOT NULL,
    jumlah integer NOT NULL
);


ALTER TABLE public.transaksi OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 40969)
-- Name: transaksi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaksi ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.transaksi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4841 (class 0 OID 32777)
-- Dependencies: 215
-- Data for Name: produk; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.produk VALUES (6, 'Garam Beryodium', '500 g', 3000, 3500, 270);
INSERT INTO public.produk VALUES (7, 'Air Mineral', '1 L', 3500, 5000, 68);
INSERT INTO public.produk VALUES (1, 'Minyak Goreng Sari', '1 L', 20000, 23000, 120);
INSERT INTO public.produk VALUES (5, 'Tepung Terigu Lestari', '1 kg', 8000, 9500, 108);
INSERT INTO public.produk VALUES (3, 'Gula Manis Indah', '1 kg', 13000, 15000, 145);


--
-- TOC entry 4844 (class 0 OID 40970)
-- Dependencies: 218
-- Data for Name: transaksi; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.transaksi OVERRIDING SYSTEM VALUE VALUES (7, 'Antonius', 1, '2024-11-03', 15);
INSERT INTO public.transaksi OVERRIDING SYSTEM VALUE VALUES (8, 'Antonius', 3, '2024-11-03', 20);
INSERT INTO public.transaksi OVERRIDING SYSTEM VALUE VALUES (9, 'Anton', 7, '2024-11-03', 20);
INSERT INTO public.transaksi OVERRIDING SYSTEM VALUE VALUES (10, 'Anton', 3, '2024-11-03', 30);
INSERT INTO public.transaksi OVERRIDING SYSTEM VALUE VALUES (11, 'Dimas', 6, '2024-11-03', 30);
INSERT INTO public.transaksi OVERRIDING SYSTEM VALUE VALUES (12, 'asci', 7, '2024-11-03', 12);
INSERT INTO public.transaksi OVERRIDING SYSTEM VALUE VALUES (13, 'Antonius', 1, '2024-11-04', 15);
INSERT INTO public.transaksi OVERRIDING SYSTEM VALUE VALUES (14, 'Antonius Sebastian', 5, '2024-11-04', 12);
INSERT INTO public.transaksi OVERRIDING SYSTEM VALUE VALUES (15, 'Antonius Sebastian', 3, '2024-11-04', 5);


--
-- TOC entry 4851 (class 0 OID 0)
-- Dependencies: 216
-- Name: produk_no_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produk_no_seq', 7, true);


--
-- TOC entry 4852 (class 0 OID 0)
-- Dependencies: 217
-- Name: transaksi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaksi_id_seq', 15, true);


--
-- TOC entry 4693 (class 2606 OID 32781)
-- Name: produk produk_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produk
    ADD CONSTRAINT produk_pkey PRIMARY KEY (no);


--
-- TOC entry 4695 (class 2606 OID 40974)
-- Name: transaksi transaksi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaksi
    ADD CONSTRAINT transaksi_pkey PRIMARY KEY (id);


--
-- TOC entry 4697 (class 2620 OID 40981)
-- Name: transaksi update_stock; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_stock AFTER INSERT ON public.transaksi FOR EACH ROW EXECUTE FUNCTION public.update_stock_after_insert();


--
-- TOC entry 4696 (class 2606 OID 40975)
-- Name: transaksi no_produk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaksi
    ADD CONSTRAINT no_produk FOREIGN KEY (no_produk) REFERENCES public.produk(no) NOT VALID;


-- Completed on 2024-11-04 13:38:07

--
-- PostgreSQL database dump complete
--

